<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>H0sin</Authors>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\Cyrus.Core.Plugins\Cyrus.Core.Plugins.csproj" />
        <ProjectReference Include="..\..\Core\Cyrus.Core.Contracts\Cyrus.Core.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    </ItemGroup>
</Project>